# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-20 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Diff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_student', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('block_no', models.CharField(max_length=1, null=True)),
                ('capacity', models.IntegerField(default=3)),
                ('vacancy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('join_year', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200, null=True)),
                ('f_name', models.CharField(max_length=200, null=True)),
                ('batch', models.IntegerField(default=2016)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('reg_date', models.DateField(null=True)),
                ('fee_receipt', models.CharField(max_length=20, null=True)),
                ('per_address', models.TextField(null=True)),
                ('roll_no', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('graduate', models.BooleanField(default=False)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student2', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=300)),
                ('accept', models.BooleanField(default=False)),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.Student')),
            ],
        ),
        migrations.AddField(
            model_name='change',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.Student'),
        ),
    ]
