# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_remove_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='f_name',
            new_name='father_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reg_date',
        ),
    ]
