# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_auto_20181021_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.AlterField(
            model_name='student',
            name='join_year',
            field=models.IntegerField(default=2016),
        ),
    ]
