# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_auto_20181021_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='graduate',
        ),
    ]
