# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_auto_20181023_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_receipt',
            field=models.FileField(max_length=20, null=True, upload_to=b''),
        ),
    ]
