# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_auto_20181023_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gradute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='vacancy',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='fee_receipt',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
