# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_auto_20181025_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gradute',
            new_name='graduate',
        ),
    ]
