# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_auto_20181025_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='graduate',
        ),
    ]
