# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_auto_20181026_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swap',
            name='student2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.Swaphelper'),
        ),
    ]
