# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_auto_20181026_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_receipt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='swap',
            name='student2',
            field=models.CharField(max_length=300),
        ),
    ]
