# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-27 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_auto_20181026_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='per_address',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pincode',
            field=models.IntegerField(default=382009),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
