# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_auto_20181027_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_receipt',
            field=models.FileField(null=True, upload_to='receipt/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
    ]
