# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-27 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0017_auto_20181027_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swap',
            name='student1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student1', to='hostel.Student'),
        ),
        migrations.AlterField(
            model_name='swap',
            name='student2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student2', to='hostel.Student'),
        ),
    ]
